### PR TITLE
fix: Json(Object) is not correct when f32 type in Object, when project use serde_json's "arbitrary_precision" feature.

### PR DESCRIPTION
**Pull request by aweika**
cargo.toml：
```
...
serde_json = { version = "1.0.104", features = ["arbitrary_precision"] }
```
test code：
```
use poem::{listener::TcpListener, Route, Server};
use poem::Result;
use poem_openapi::{payload::Json, ApiResponse, OpenApi, OpenApiService};

struct Api;


#[derive(ApiResponse)]
enum TestResponse {
    #[oai(status = 200)]
    Ok(Json<Vec<f32>>),
}

#[OpenApi]
impl Api {
    #[oai(path = "/hello", method = "get")]
    async fn index(&self) -> Result<TestResponse> {
        let test_arr = vec![32.1, 32.2];
        Ok(TestResponse::Ok(Json(test_arr)))
    }
}

#[tokio::main]
async fn main() -> Result<(), std::io::Error> {
    if std::env::var_os("RUST_LOG").is_none() {
        std::env::set_var("RUST_LOG", "poem=debug");
    }
    tracing_subscriber::fmt::init();

    let api_service =
        OpenApiService::new(Api, "Hello World", "1.0").server("http://localhost:3000/api");
    let ui = api_service.swagger_ui();

    Server::new(TcpListener::bind("127.0.0.1:3000"))
        .run(Route::new().nest("/api", api_service).nest("/", ui))
        .await
}
```
I want got:
```
[
  32.1,
  32.2
]
```
But I got response:
```
[
  32.099998474121094,
  32.20000076293945
]
```

the commit is fixed the problem.

### CODE REVIEW

**Comment by sunli829** [comment]
Thanks for the PR! 🙂

I think we can add a new feature called `arbitrary_precision` to the `Poem-openapi`,  and then enable `serde_json/arbitrary_precision` when the user enables it on `Poem-openapi`, what do you think? 

```toml
[features]
arbitrary_precision = ["serde_json/arbitrary_precision"]
```

**Comment by aweika** [comment]
@sunli829 I think it's good.

**Comment by sunli829** [comment]
If it's convenient, can you help me add a description of this feature to [README.md](https://github.com/poem-web/poem/blob/master/poem/README.md#crate-features) and [lib.rs](https://github.com/poem-web/poem/blob/27a77b76fda17314b4a4d2d688d6167c64ba6ef3/poem/src/lib.rs#L226)?  🙂

**Comment by aweika** [comment]
I added a description of the feature to README.md and lib.rs under the poem-openapi folder.

**Comment by sunli829** [comment]
Thanks😄

**Comment by sunli829** [comment]
`arbitrary_precision` caused some other problems, which I will look into again.

**Comment by aweika** [comment]
Ok, I'll try to use `f64` . Thank

**Pull request merged**
