### PR TITLE
Demonstrate how to add headers to the response with a custom response type

### PR DESCRIPTION
**Pull request by banool**
Hey, I'm trying to figure out how to add headers to a custom response type. I'm trying to modify an example to demonstrate how to do this. As you can see, I'm trying many different options, but I can't figure out how to do it properly. I see in some other parts of the codebase that you wrap the custom response type with `Response`, but I would like to keep the same return type for `get`, and just inject headers somehow. 

I feel like perhaps if you derive `ApiResponse`, it should expose a function to add headers, just like with the regular `Response` object. Does that make sense? If so, I can take a look at adding support for this.

### CODE REVIEW

**Comment by sunli829** [comment]
You should use `header` attribute to add a header, then it can shown in Swagger.

https://github.com/poem-web/poem/blob/cd27094b82bc07dfaf2cc87690b59a5cb4c7058d/poem-openapi/tests/response.rs#L105

**Comment by banool** [comment]
Oh awesome this makes sense, I'll take it for a spin.

**Comment by banool** [comment]
I updated the example :)

**Comment by banool** [comment]
Hey @sunli829 do you think we could land this? It should be good to go.

**Comment by sunli829** [comment]
Thanks! 🙂

**Pull request merged**
