### PR TITLE
[eyre06] Integration with eyre 0.6 similarly to anyhow

### PR DESCRIPTION
**Pull request by kolloch**
I hope, this makes sense to you! It would make using eyre with poem much more convenient.

This is obviously trivial code mostly copied from the `anyhow` integration code.

https://github.com/poem-web/poem/issues/189

### CODE REVIEW

**Comment by sunli829** [comment]
Looks great!👏

**Comment by kolloch** [comment]
Awesome! Tell me if you need something else for me to get this merged. @sunli829 

Probably, I should add docs for the feature flag or so.

**Comment by sunli829** [comment]
Thanks a lot, please help me add documentation. 🙂

https://github.com/poem-web/poem/blob/2e08a49adb42cce4332539f281c3f529c9a97fd9/poem/README.md?plain=1#L70

https://github.com/poem-web/poem/blob/2e08a49adb42cce4332539f281c3f529c9a97fd9/poem/src/lib.rs#L244

**Comment by kolloch** [comment]
> Thanks a lot, please help me add documentation. slightly_smiling_face
Done :)

**Pull request merged**
