### PR TITLE
Support for custom hash functions for HashMap

### PR DESCRIPTION
**Pull request by a14e**
In this pull request, I added a generic parameter to all HashMap traits to support the custom Hash function. In my case, I wanted to add support for `ahash`.

### CODE REVIEW

**Comment by a14e** [comment]
@sunli829 could you please take a look?

**Comment by sunli829** [comment]
Thank you very much, I believe other containers have similar problems, such as `HashSet`, it would be great if you could help me fix it. 🙂

PS: format the code using `rust +nightly fmt`

**Comment by a14e** [comment]
@sunli829 done

**Comment by sunli829** [comment]
thanks😁

**Pull request merged**
