### PR TITLE
Upgrade sqlx to 0.6.0

### PR DESCRIPTION
**Pull request by phungleson**
As described.

### CODE REVIEW

**Comment by phungleson** [comment]
Hey @sunli829 I am not entirely sure why checks failed, they seem to run fine in my local.

**Comment by phungleson** [comment]
Ok upgrade toolchain to `1.61.0 ` works

**Comment by Christoph-AK** [comment]
Wouldn't this increase the MSRV to 1.61 then? If so it seems like a breaking change.

**Comment by phungleson** [comment]
Yeah true, I am not sure how big the change is.

@sunli829 probably can advise, I am happy to make all changes, or wait for this.

**Comment by sunli829** [comment]
I'd happily upgrade to Rust 1.61 🙂

**Pull request merged**
