### PR TITLE
Allow optional prefix in generated spec

### PR DESCRIPTION
**Pull request by VersBinarii**
This PR addresses this [issue](https://github.com/poem-web/poem/issues/470).

@sunli829  please review and let me know if this is ok with you

### CODE REVIEW

**Comment by VersBinarii** [comment]
The tests are failing because some rate limits while installing protoc

**Comment by VersBinarii** [comment]
@sunli829 if you're happy with the approach i could add the options to the `swagger_ui` and `rapidoc` functions as well.

**Comment by sunli829** [comment]
Maybe it's better to do this?

```rust
 let api_service = OpenApiService::new(TodosApi, "Todos", "1.0.0")
                              .server("http://localhost:3000")
                              .url_prefix("/foo/bar"); // specified url prefix
```

**Comment by VersBinarii** [comment]
Very well, that seems cleaner. Let me have a look at it then

**Comment by VersBinarii** [comment]
Hello @sunli829 , i've updated it as per your suggestion.

**Comment by sunli829** [comment]
Thanks! 🙂

**Pull request merged**
