### PR TITLE
feat(openapi): added example value support for param/schema

### PR DESCRIPTION
**Pull request by chirag-droid**
## Example Code

image

```rs
struct Api;

fn hello_world() -> String { String::from("Hello World") }

#[OpenApi]
impl Api {
    #[oai(path = "/", method = "get")]
    async fn get(
        &self,
        #[oai(example = "hello_world")] name: Query<String>,
    ) -> PlainText(String) {
        PlainText(name.0)
    }
}
```

### CODE REVIEW

**Comment by chirag-droid** [comment]
I have also added test for it in `poem-openapi/tests/operation_param.rs`

**Comment by attila-lin** [comment]
fmt failed~

**Comment by chirag-droid** [comment]
let me fix it. there should be a git pre commit hook for this.

**Comment by sunli829** [comment]
thanks! 🙂

**Pull request merged**
