### PR TITLE
feat: Replace `serde_json` with `sonic_rs` for `poem` crate

### PR DESCRIPTION
**Pull request by Mr-Leshiy**
Refactored `poem` crate, replaced at some places usage of `serde_json` with the more faster json serde crate `sonic_rs`.

I've locally benchmarked a simple `poem` service like this
```
use poem::{handler, listener::TcpListener, post, web::Json, Route, Server};

#[handler]
fn echo(val: Json<serde_json::Value>) -> Json<serde_json::Value> {
    val
}

#[tokio::main]
async fn main() -> Result<(), std::io::Error> {
    let app = Route::new().at("/echo", post(echo));
    Server::new(TcpListener::bind("0.0.0.0:3000"))
      .run(app)
      .await
}
```
With the help of `locust` I've got a 20% decrease of response time, with the following benchmark.
```
from locust import FastHttpUser, task
import json

# Opening JSON file
f = open('large-file.json')
data = json.load(f)


class HelloWorldUser(FastHttpUser):
    @task
    def hello_world(self):
        self.client.post(
            "/echo",
            json=data
        )
```

[large-file.json](https://github.com/poem-web/poem/files/15363214/large-file.json)

# Issue 

https://github.com/poem-web/poem/issues/813

### CODE REVIEW

**Comment by attila-lin** [comment]
How about be a feature?

Someone may not care about the performance.

**Comment by Mr-Leshiy** [comment]
@attila-lin updated it with adding a new feature flag `sonic-rs`.
Should I also put some notes in somewhere in docs about this new feature ?

**Comment by Mr-Leshiy** [comment]
@attila-lin
So sorry for the delay, forgot about this PR.
I've updated corresponded `README.md` files and rust docs.

**Comment by attila-lin** [comment]
I'd like to merge this. Any suggestions? @sunli829

**Comment by sunli829** [comment]
does `sonic-rs` only work with nightly Rust?

**Comment by Mr-Leshiy** [comment]
@sunli829 no, it works on stable one

**Comment by sunli829** [comment]
```
error[E0658]: use of unstable library feature 'result_option_inspect'
  --> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sonic-rs-0.3.12/src/reader.rs:73:21
   |
73 |         self.peek().inspect(|_| {
   |                     ^^^^^^^
   |
   = note: see issue #91345 <https://github.com/rust-lang/rust/issues/91345> for more information
```

**Pull request merged**
