### PR TITLE
Add support for wildcard '*' in cors domains

### PR DESCRIPTION
**Pull request by Sagebati**
Hi ! 

This new feature is especially useful for applications that utilize multiple subdomains, as it eliminates the need to manually configure CORS for each subdomain. By simply adding the wildcard (*) to your CORS configuration, you can enable cross-domain requests for all subdomains of a given domain. I replaced the `HashSet::contains` search with a Regex containing all the domains (example:https://regex101.com/r/ZEhBy4/2).  I'm aware of `the allow_origin_fn`, but in opinion this is ergonomic.  The PR is almost ready to be merged only need a review of the `unwrap` used.

Any feedback is welcome.

### CODE REVIEW

**Comment by attila-lin** [comment]
Hi, @Sagebati , Thank you for your mr.

Would you please add some testcase and fix the CI?

**Comment by Sagebati** [comment]
Hi, I corrected the CI errors.

**Comment by Sagebati** [comment]
Seems like the CI passes

**Review by DDtKey — COMMENTED** [review]
Just a suggestion: consider to use a [wildmatch](https://crates.io/crates/wildmatch) crate

**Comment by Sagebati** [comment]
I didn't knew this crate, I could rewrite the feature to use it. The change that it implies is we will have a `Vec<WildMatch>` instead of only one regex, but it easier to maintain. Let met know your preferences

**Comment by sunli829** [comment]
What do you think if it could be better like below? @Sagebati 

```rust
pub struct Cors {
    allow_credentials: bool,
    allow_origins: HashSet<HeaderValue>,
    allow_origins_wildcard: Vec<WildMatch>, //////// <<<<<<<<<
    allow_origins_fn: Option<Arc<dyn Fn(&str) -> bool + Send + Sync>>,
    allow_headers: HashSet<HeaderName>,
    allow_methods: HashSet<Method>,
    expose_headers: HashSet<HeaderName>,
    max_age: i32,
}

impl Cors {
    fn allow_origin_to_regex(mut self, wildcard: impl AsRef<str>) -> Self {
        self.allow_origins_wildcard.push(WildMatch::new(wildcard));
        self
    }
}
```

**Comment by sunli829** [comment]
Could you help to add a test case? 🙂 @Sagebati

**Comment by sunli829** [comment]
Thanks! @Sagebati  🙂

**Pull request merged**
