### PR TITLE
Bumping the minimal version of Rust

### PR DESCRIPTION
**Pull request by Mr-Leshiy**
Fixes https://github.com/poem-web/poem/issues/732 which is still relevant and could be easily reproducible.

Bumped `rust-version` in `Cargo.toml` file to `1.74` version, look https://github.com/rust-lang/rust/pull/115453.

### CODE REVIEW

**Comment by attila-lin** [comment]
Nice catch.

Thank you.

**Comment by attila-lin** [comment]
Do you mind update the readme rustc together? @Mr-Leshiy

**Comment by Mr-Leshiy** [comment]
@attila-lin Already, done 😊

**Comment by attila-lin** [comment]
Thanks a lot~

**Pull request merged**
