### PR TITLE
fix(prometheus): use correct `content-type` header

### PR DESCRIPTION
**Pull request by SimenB**
The header should include the version.

https://prometheus.io/docs/instrumenting/exposition_formats/#text-based-format

https://docs.rs/prometheus/0.13.4/src/prometheus/encoder/text.rs.html#12-13

### CODE REVIEW

**Comment by attila-lin** [comment]
Would you mind add some test case?

**Comment by SimenB** [comment]
added 👍

**Comment by SimenB** [comment]
hah, didn't notice the formatting thing. fix pushed

**Comment by attila-lin** [comment]
Thanks！

**Pull request merged**
